Configure default locale in Vagrant and keep it under SSH
Otherwise the locale of the user invoking `vagrant ssh` may be used instead,
and cause problems if it does not exist in the VM.

For instance, my `ca_ES.UTF-8` locale caused the following error while
unpacking Go 1.12.3 (which contains test files with non-ASCII names): `CMake
Error: Problem with archive_read_next_header(): Pathname can't be converted
from UTF-8 to current locale.`