Use templates instead of `auto` in temp/atomic file R/W op decls.
They caused the Android build to fail with:

    error: 'auto' not allowed in function prototype